#!/bin/sh

PKG_NAME=$(basename "$SYNOPKG_PKGDEST")
TARGET_DIR="/var/packages/$PKG_NAME/target"
UI_DIR="$TARGET_DIR/ui"
TEXTS_DIR="$TARGET_DIR/ui/texts"
VAR_DIR="/var/packages/$PKG_NAME/var"

# Remove spurious files injected by the package builder
rm -f  "$UI_DIR/Makefile"
rm -f  "$UI_DIR/ui"  # self-referencing symlink
rm -f  "$TEXTS_DIR/strings"  # strings file template

exit 0
